wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1632413152
    t:
      4: 3.8.5
      5: 0.12.2
      8:
      - 1
      - 5
